version: '3'

services:
  comparaisonrisques:
    image: sepulwarrior/comparaisonrisques:prototype-windows
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"
networks:
  default:
    external:
      name: nat
